### ISSUE TITLE
Non-grouping field 'relevance' is used in HAVING clause"

### ISSUE THREAD

**Issue by zwl1619** [TomLingham/Laravel-Searchy#62] opened 2016-11-27 19:24 UTC
I am using Laravel `5.3`.   
I have disabled strict mode.     
```
        'mysql' => [
            //...
            'strict' => false,
           //...
        ]
```
**Query:**
```
$articles = \Searchy::articles('title', 'content')->query($keywords)->get();
```
**Result:**
```
QueryException in Connection.php line 761:
SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'relevance' is used in HAVING clause (SQL: select *, IF(COALESCE(`title`, '') = 'book', 100, 0) + IF(COALESCE(`title`, '') LIKE 'book%', 50, 0) + IF(COALESCE(`title`, '') LIKE 'B% O% O% K%', 42, 0) + IF( REPLACE(COALESCE(`title`, ''), '\.', '') LIKE '%b%o%o%k%', ROUND(40 * ( CHAR_LENGTH( 'book' ) / CHAR_LENGTH( REPLACE(COALESCE(`title`, ''), ' ', '') ))), 0) + IF(COALESCE(`title`, '') LIKE 'book%', 35, 0) + IF( CHAR_LENGTH( TRIM( COALESCE(`title`, '') )) = CHAR_LENGTH( REPLACE( TRIM( COALESCE(`title`, '') ), ' ', '')) AND COALESCE(`title`, '') LIKE BINARY 'B%O%O%K%', 32, 0) + IF(COALESCE(`title`, '') LIKE '%book%', 30, 0) + 8 * ROUND((
CHAR_LENGTH(COALESCE(`title`, '')) - CHAR_LENGTH( REPLACE( LOWER(COALESCE(`title`, '')), lower('book'), ''))
) / LENGTH('book')) + IF(COALESCE(`content`, '') = 'book', 100, 0) + IF(COALESCE(`content`, '') LIKE 'book%', 50, 0) + IF(COALESCE(`content`, '') LIKE 'B% O% O% K%', 42, 0) + IF( REPLACE(COALESCE(`content`, ''), '\.', '') LIKE '%b%o%o%k%', ROUND(40 * ( CHAR_LENGTH( 'book' ) / CHAR_LENGTH( REPLACE(COALESCE(`content`, ''), ' ', '') ))), 0) + IF(COALESCE(`content`, '') LIKE 'book%', 35, 0) + IF( CHAR_LENGTH( TRIM( COALESCE(`content`, '') )) = CHAR_LENGTH( REPLACE( TRIM( COALESCE(`content`, '') ), ' ', '')) AND COALESCE(`content`, '') LIKE BINARY 'B%O%O%K%', 32, 0) + IF(COALESCE(`content`, '') LIKE '%book%', 30, 0) + 8 * ROUND((
CHAR_LENGTH(COALESCE(`content`, '')) - CHAR_LENGTH( REPLACE( LOWER(COALESCE(`content`, '')), lower('book'), ''))
) / LENGTH('book')) AS relevance from `articles` where `deleted_at` is null having `relevance` > 0 order by `relevance` desc)
```

**Comment by dejury** [comment] 2017-03-24 11:06
I had the same issue. Changed the strict to false, and it was still not working.

After doing: 
`php artisan config:clear `

It worked fine for me. Maybe this is the issue?

**Comment by TomLingham** [comment] 2017-05-03 11:59
Duplicate of #60

**Closed by TomLingham** 2017-05-03 11:59 UTC
